
import React from 'react';

interface LandingProps {
  onStart: () => void;
}

const Landing: React.FC<LandingProps> = ({ onStart }) => {
  return (
    <div className="max-w-4xl mx-auto flex flex-col items-center text-center py-12 px-4">
      <div className="mb-8 inline-block p-4 bg-indigo-50 rounded-full text-indigo-600">
        <i className="fas fa-robot text-5xl"></i>
      </div>
      
      <h1 className="text-5xl md:text-6xl font-extrabold mb-6 text-gray-900 leading-tight">
        Master the Art of <span className="gradient-text">Visual Prompting</span>
      </h1>
      
      <p className="text-xl text-gray-600 mb-12 max-w-2xl leading-relaxed">
        Improve your observation skills and learn how to describe images for AI. 
        Level up through 5 challenges, from simple objects to cinematic scenes.
      </p>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-16 w-full">
        <FeatureCard 
          icon="fa-binoculars" 
          title="Observe" 
          description="Look closely at the reference image generated by AI."
        />
        <FeatureCard 
          icon="fa-pen-fancy" 
          title="Describe" 
          description="Write a prompt that captures every detail you see."
        />
        <FeatureCard 
          icon="fa-bullseye" 
          title="Match" 
          description="Generate your own AI image and see how close you got!"
        />
      </div>

      <button
        onClick={onStart}
        className="group relative inline-flex items-center justify-center px-10 py-4 font-bold text-white transition-all duration-200 bg-indigo-600 font-pj rounded-full focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-600 hover:bg-indigo-700 shadow-xl hover:shadow-indigo-200"
      >
        Get Started
        <i className="fas fa-arrow-right ml-2 group-hover:translate-x-1 transition-transform"></i>
      </button>
    </div>
  );
};

const FeatureCard: React.FC<{ icon: string; title: string; description: string }> = ({ icon, title, description }) => (
  <div className="p-6 bg-white rounded-2xl shadow-sm border border-gray-100 text-center">
    <div className="w-12 h-12 bg-indigo-50 rounded-xl flex items-center justify-center text-indigo-600 mx-auto mb-4">
      <i className={`fas ${icon} text-xl`}></i>
    </div>
    <h3 className="text-lg font-bold text-gray-900 mb-2">{title}</h3>
    <p className="text-gray-500 text-sm">{description}</p>
  </div>
);

export default Landing;
